# render.yaml
services:
  - type: web
    name: cyber-jaguar
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: GMAIL_USERNAME
        sync: false
      - key: GMAIL_PASSWORD
        sync: false
      - key: RACK_ENV
        value: production
      - key: RAILS_ENV
        value: production
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: RAILS_SERVE_STATIC_FILES
        value: true